linters-settings:
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    enable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  funlen:
    lines: 100
    statements: 50
  godot:
    capital: true
  unparam:
    check-exported: true

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec # security check is not impoerant in tests
        - dupl # we usualy duplicate code in tests
        - bodyclose
        - unparam
  fix: true
  new-from-rev: f7ba36ac19758ed7c294e6e61630ce77a61f234f

run:
  skip-dirs:
    - model
    - tmp
    - bin
    - scripts

  tests: true
  build-tags:
    - integration

linters:
  disable-all: true
  fast: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - depguard
    - dupl
    - errorlint
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    # - misspell # disabled as it was breaking interfaces with FinaliZe
    - nakedret
    - nestif
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    # - unparam # Too many false positives on Task interface implementation.
    - unused
    - whitespace
    # - wrapcheck
    - tparallel

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.38.x
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
