linters-settings:
  govet:
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    enable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: UK
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  funlen:
    lines: 100
    statements: 50
  godot:
    capital: true
  unparam:
    check-exported: true

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec # security check is not important in tests
        - dupl # we usualy duplicate code in tests
        - bodyclose
        - unparam
        - errcheck
        - govet
  fix: true
  exclude-use-default: false

run:
  build-tags:
    - integration
    - e2e
  skip-dirs:
    - model
    - tmp
    - bin
    - scripts
    - test
  tests: true

linters:
  disable-all: true
  fast: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - nilerr
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.43.x
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"
